export { testConnection } from './auth/testConnection'
export { submitScrobble } from './scrobble'
export { submitNowPlaying } from './nowPlaying'
export { getLBSimilarArtists } from './recommendations/getSimilarArtists'
export type { LBSimilarArtist } from './recommendations/getSimilarArtists'
