export { testConnection } from './auth/testConnection'
export { submitScrobble } from './scrobble'
export { submitNowPlaying } from './nowPlaying'
export { getRecommendedRecordings } from './recommendations/getRecommendedRecordings'
export { getLBSimilarArtists } from './recommendations/getSimilarArtists'
export { getUserRecommendedPlaylists } from './recommendations/getUserRecommendedPlaylists'
export type { LBRecommendedRecording } from './recommendations/getRecommendedRecordings'
export type { LBSimilarArtist } from './recommendations/getSimilarArtists'
export type { LBRecommendedPlaylist } from './recommendations/getUserRecommendedPlaylists'
