export const ALBUM_RECOMMENDATION_HORIZONTAL_PADDING = 16;
export const ALBUM_RECOMMENDATION_TILE_GAP = 12;
export const ALBUM_RECOMMENDATION_VISIBLE_TILES = 2.5;
export const ALBUM_RECOMMENDATION_RELATED_LIMIT = 30;
export const ALBUM_RECOMMENDATION_TARGET_ALBUMS = 8;

export const ALBUM_ESTIMATED_ROW_HEIGHT = 72;
export const ALBUM_DISC_HEADER_HEIGHT = 36;
