export const HOME_TARGET_ALBUMS = 10;
export const HOME_RELATED_ARTIST_LIMIT = 40;
export const HOME_SEED_ARTISTS = 4;
export const HOME_RELATED_PER_SEED = 12;
export const HOME_GENRE_ARTIST_LIMIT = 40;

export const QUICK_PICKS_PAGE_SIZE = 4;
export const QUICK_PICKS_TOTAL_PAGES = 3;
export const QUICK_PICKS_TOTAL = QUICK_PICKS_PAGE_SIZE * QUICK_PICKS_TOTAL_PAGES;
export const QUICK_PICKS_CANDIDATE_POOL = QUICK_PICKS_TOTAL * 2;
export const QUICK_PICKS_DECAY_MS = 7 * 24 * 60 * 60 * 1000;
export const QUICK_PICKS_PEEK = 28;
