export const HOME_TARGET_ALBUMS = 10;
export const HOME_RELATED_ARTIST_LIMIT = 40;
export const HOME_SEED_ARTISTS = 4;
export const HOME_RELATED_PER_SEED = 12;
export const HOME_GENRE_ARTIST_LIMIT = 40;

export const QUICK_PICKS_PAGE_SIZE = 4;
export const QUICK_PICKS_TOTAL_PAGES = 3;
export const QUICK_PICKS_TOTAL = QUICK_PICKS_PAGE_SIZE * QUICK_PICKS_TOTAL_PAGES;
export const QUICK_PICKS_CANDIDATE_POOL = QUICK_PICKS_TOTAL * 2;
export const QUICK_PICKS_DECAY_MS = 7 * 24 * 60 * 60 * 1000;
export const QUICK_PICKS_PEEK = 28;

export const HOME_MIN_ALBUMS = 8;
export const HOME_MAX_ALBUMS = 10;
export const HOME_MIN_FAVORITE_ALBUMS = 8;
export const HOME_MAX_FAVORITE_ALBUMS = 10;
export const HOME_MIN_MOST_PLAYED_ALBUMS = 4;
export const HOME_MAX_MOST_PLAYED_ALBUMS = 10;
export const HOME_RECENTLY_PLAYED_HORIZONTAL_PADDING = 12;
export const HOME_RECENTLY_PLAYED_GAP = 10;
export const HOME_RECENTLY_PLAYED_VISIBLE_ITEMS = 3.2;
export const HOME_RECENTLY_PLAYED_MAX_ITEMS = 12;
export const HOME_RECENTLY_PLAYED_MIN_ITEMS = 1;
export const HOME_SECTION_HORIZONTAL_PADDING = 12;
